#!/bin/bash
### Install updates and mail utils

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y dist-upgrade
apt-get install -y python-software-properties nfs-common netcat-openbsd mutt
apt-get -y -f install
apt-get -y install postfix mailutils ntp

### Setup timezone

mv /etc/localtime /etc/localtime.bak
ln -s /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
dpkg-reconfigure -fnoninteractive tzdata


##### sysctl config####

cat > /etc/sysctl.conf <<DELIM
net.ipv4.conf.all.accept_source_route=0
net.ipv4.conf.lo.accept_source_route=0
net.ipv4.conf.eth0.accept_source_route=0
net.ipv4.conf.default.accept_source_route=0
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.lo.accept_redirects=0
net.ipv4.conf.eth0.accept_redirects=0
net.ipv4.conf.default.accept_redirects=0
net.ipv4.conf.all.secure_redirects=0
net.ipv4.conf.default.secure_redirects=0

net.ipv6.conf.all.accept_redirects=0

net.ipv4.conf.all.send_redirects=0
# net.ipv4.icmp_echo_ignore_all=1
DELIM

sysctl -p




cat > /etc/securetty <<DELIM
## ==========================================================
##
## TTYs sorted by major number according to Documentation/devices.txt
##
## ==========================================================

## Virtual consoles
tty1
tty2
tty3
tty4
tty5
tty6
tty7
tty8
tty9
DELIM


sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
rm -f /etc/update-motd.d/00-netflix
rm -f /etc/update-motd.d/1*
rm -f /etc/update-motd.d/5*


### Set motd

cat >> /etc/update-motd.d/00-netflix << 'DELIM'
#!/bin/bash

let upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
let secs=$((${upSeconds}%60))
let mins=$((${upSeconds}/60%60))
let hours=$((${upSeconds}/3600%24))
let days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`

## get the load averages

read one five fifteen rest < /proc/loadavg

echo "$(tput setaf 2)    

| \ | | ___| |_ / _| (_)_  __ 
|  \| |/ _ \ __| |_| | \ \/ /
| |\  |  __/ |_|  _| | |>  < 
|_| \_|\___|\__|_| |_|_/_/\_\ [ITOps in Amazon!]

`date +"%A, %e %B %Y, %r"`
`lsb_release -dc`$(tput setaf 1)

Uptime.............: ${UPTIME}
Memory.............: `cat /proc/meminfo | grep MemFree | awk {'print $2'}`kB (Free) / `cat /proc/meminfo | grep MemTotal | awk {'print $2'}`kB (Total)
Load Averages......: ${one}, ${five}, ${fifteen} (1, 5, 15 min)
Running Processes..: `ps ax | wc -l | tr -d " "`
IP Addresses(eth0).: `/sbin/ifconfig eth0 | /bin/grep "inet addr" | /usr/bin/cut -d ":" -f 2 | /usr/bin/cut -d " " -f 1`
$(tput sgr0)"
DELIM

chmod 755 /etc/update-motd.d/00-netflix

echo "umask 077" >> /etc/skel/.profile
echo "umask 077" >> /root/.profile
echo "umask 077" >> /home/ubuntu/.profile 


if [[ -d "/etc/network/interfaces.d" ]]; then
  echo "dns-search itp.netflix.com itd.netflix.com its.netflix.com netflix.com eng.netflix.com prod.netflix.com" >> /etc/network/interfaces.d/eth0.cfg
    else
    echo "dns-search itp.netflix.com itd.netflix.com its.netflix.com netflix.com eng.netflix.com prod.netflix.com" >> /etc/network/interfaces
fi

#### Install cloud passage ###
echo 'deb http://packages.cloudpassage.com/debian debian main' | tee /etc/apt/sources.list.d/cloudpassage.list > /dev/null

# import CloudPassage public key
curl http://packages.cloudpassage.com/cloudpassage.packages.key | apt-key add -

# install the daemon, but do not start it
dpkg --configure -a
apt-get update
echo -e '#!/bin/sh\nexit 101' | install -m 755 /dev/stdin /usr/sbin/policy-rc.d && apt-get -y install cphalo && rm -f /usr/sbin/policy-rc.d
dpkg --configure -a
  
# start the daemon for the first time
while true
     do
     ([[ -f /opt/cloudpassage/data/halo.pid ]]) && break
     if [[ "$HOSTNAME" =~ bastion ]]; then
         /etc/init.d/cphalod start --daemon-key=155794252cf3f225dc2e36c4236b03e1 --tag=bastion
     else 
         /etc/init.d/cphalod start --daemon-key=155794252cf3f225dc2e36c4236b03e1
     fi
     sleep 2
done
      
# dpkg gets wacky at this point
dpkg --configure -a
apt-get -y -f install
